/*=========================================================
PROYECTO: ATLAS

ARCHIVO: productos.js

FUNCIÓN:
Almacena la información del catálogo.
Este archivo puede ser actualizado por ATLAS Gestor Local.
=========================================================*/

const productos = [
    {
        "id": 1,
        "codigo": "ATL-SNK-001",
        "marca": "Nike",
        "modelo": "Nike Retro 1 Dior",
        "color": "Azul, gris y blanco",
        "tipo": "Réplica",
        "precio": 210000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker de estilo urbano con silueta retro y una combinación de tonos azules, grises y blancos.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-001/atl-snk-001-01.jpeg",
            "img/productos/atl-snk-001/atl-snk-001-02.jpeg",
            "img/productos/atl-snk-001/atl-snk-001-03.jpeg"
        ],
        "estado": "disponible",
        "destacado": true,
        "fechaCreacion": "2026-07-27",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 2,
        "codigo": "ATL-SNK-002",
        "marca": "Adidas",
        "modelo": "Adidas Yeezy",
        "color": "Gris, negro, verde, azul y naranja",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker de perfil robusto y estética deportiva, presentado en una combinación multicolor.",
        "categoria": "Deportivo",
        "imagenes": [
            "img/productos/atl-snk-002/atl-snk-002-01.jpeg",
            "img/productos/atl-snk-002/atl-snk-002-02.jpeg",
            "img/productos/atl-snk-002/atl-snk-002-03.jpeg",
            "img/productos/atl-snk-002/atl-snk-002-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": true,
        "fechaCreacion": "2026-07-27",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 3,
        "codigo": "ATL-SNK-003",
        "marca": "Clemont",
        "modelo": "Clemont",
        "color": "Negro y rojo",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker urbano negro con detalles rojos de alto contraste y una estética fuerte y distintiva.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-003/atl-snk-003-01.jpeg",
            "img/productos/atl-snk-003/atl-snk-003-02.jpeg",
            "img/productos/atl-snk-003/atl-snk-003-03.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-07-27",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 4,
        "codigo": "ATL-SNK-004",
        "marca": "Vans",
        "modelo": "Vans Old Skool",
        "color": "Negro",
        "tipo": "Réplica",
        "precio": 210000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker urbano en color negro total, con diseño Old Skool y acabado monocromático.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-004/atl-snk-004-01.jpeg",
            "img/productos/atl-snk-004/atl-snk-004-02.jpeg",
            "img/productos/atl-snk-004/atl-snk-004-03.jpeg",
            "img/productos/atl-snk-004/atl-snk-004-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-07-28",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 5,
        "codigo": "ATL-SNK-005",
        "marca": "Timberland",
        "modelo": "Boots Timberland",
        "color": "Amarillo Trigo",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Botas Timberland clásicas en color amarillo trigo, con un diseño icónico de caña alta, estilo robusto y versátil, ideal para combinar con atuendos urbanos y casuales.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-005/atl-snk-005-01.jpeg",
            "img/productos/atl-snk-005/atl-snk-005-02.jpeg",
            "img/productos/atl-snk-005/atl-snk-005-03.jpeg",
            "img/productos/atl-snk-005/atl-snk-005-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-07-29",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 6,
        "codigo": "ATL-SNK-006",
        "marca": "Nike",
        "modelo": "Air Jordan Retro 3",
        "color": "blanco, beige, gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Los Air Jordán 3 Retro combinan el legendario estampado de elefante con la máxima comodidad del Streetwear.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-006/atl-snk-006-01.jpeg",
            "img/productos/atl-snk-006/atl-snk-006-02.jpeg",
            "img/productos/atl-snk-006/atl-snk-006-03.jpeg",
            "img/productos/atl-snk-006/atl-snk-006-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-07-29",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 7,
        "codigo": "ATL-SNK-007",
        "marca": "On Running",
        "modelo": "On Cloudflow",
        "color": "azul, gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Corre como nunca antes con la elegancia técnica y el diseño bicolor de las On Cloudflow. La máxima potencia de la espuma Helion se une a la icónica suela CloudTec para un rendimiento explosivo",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-007/atl-snk-007-01.jpeg",
            "img/productos/atl-snk-007/atl-snk-007-02.jpeg",
            "img/productos/atl-snk-007/atl-snk-007-03.jpeg",
            "img/productos/atl-snk-007/atl-snk-007-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 8,
        "codigo": "ATL-SNK-008",
        "marca": "Puma",
        "modelo": "Puma 180",
        "color": "Gris, Blanco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Silueta *chunky* retro que fusiona malla transpirable, cuero y gamuza gris. El equilibrio perfecto entre comodidad robusta y estilo urbano.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-008/atl-snk-008-01.jpeg",
            "img/productos/atl-snk-008/atl-snk-008-02.jpeg",
            "img/productos/atl-snk-008/atl-snk-008-03.jpeg",
            "img/productos/atl-snk-008/atl-snk-008-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 9,
        "codigo": "ATL-SNK-009",
        "marca": "Osiris",
        "modelo": "Osiris",
        "color": "Negros",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Domina la calle con la legendaria silueta chunky de los Osiris, diseñados en gamuza negra con cordones blancos de alto contraste para un estilo urbano imponente.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-009/atl-snk-009-01.jpeg",
            "img/productos/atl-snk-009/atl-snk-009-02.jpeg",
            "img/productos/atl-snk-009/atl-snk-009-03.jpeg",
            "img/productos/atl-snk-009/atl-snk-009-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 10,
        "codigo": "ATL-SNK-010",
        "marca": "Boss",
        "modelo": "Hugo Boss",
        "color": "Negro, Rojo",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Destaca con la elegancia urbana de estos tenis BOSS, diseñados en negro profundo con un llamativo patrón tipográfico y exclusivos acentos en rojo vibrante.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-010/atl-snk-010-01.jpeg",
            "img/productos/atl-snk-010/atl-snk-010-02.jpeg",
            "img/productos/atl-snk-010/atl-snk-010-03.jpeg",
            "img/productos/atl-snk-010/atl-snk-010-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 11,
        "codigo": "ATL-SNK-011",
        "marca": "Nike, Supreme",
        "modelo": "Supreme x Nike Shox Ride 2",
        "color": "Rojo",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Desata tu lado más audaz con los exclusivos Supreme x Nike Shox Ride 2, una silueta retro en rojo vibrante llena de actitud streetwear.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-011/atl-snk-011-01.jpeg",
            "img/productos/atl-snk-011/atl-snk-011-02.jpeg",
            "img/productos/atl-snk-011/atl-snk-011-03.jpeg",
            "img/productos/atl-snk-011/atl-snk-011-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 12,
        "codigo": "ATL-SNK-012",
        "marca": "Le Coq Sportif",
        "modelo": "Lecoq Sportif",
        "color": "Negro",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Eleva tu estilo urbano con la elegancia atemporal de estos Le Coq Sportif, diseñados en un sofisticado negro mate con deslumbrantes acentos dorados.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-012/atl-snk-012-01.jpeg",
            "img/productos/atl-snk-012/atl-snk-012-02.jpeg",
            "img/productos/atl-snk-012/atl-snk-012-03.jpeg",
            "img/productos/atl-snk-012/atl-snk-012-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 13,
        "codigo": "ATL-SNK-013",
        "marca": "Puma",
        "modelo": "Puma Club 5v5",
        "color": "Beige, Verde",
        "tipo": "Réplica",
        "precio": 210000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Dale un toque vintage a tus pasos con esta clásica silueta de Puma, diseñada en un elegante tono crema con suaves superposiciones de gamuza y su icónica franja en contraste verde.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-013/atl-snk-013-01.jpeg",
            "img/productos/atl-snk-013/atl-snk-013-02.jpeg",
            "img/productos/atl-snk-013/atl-snk-013-03.jpeg",
            "img/productos/atl-snk-013/atl-snk-013-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 14,
        "codigo": "ATL-SNK-014",
        "marca": "Adidas, NEIGHBORHOOD",
        "modelo": "adidas Superstar",
        "color": "Negro, Blanco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker Adidas, NEIGHBORHOOD adidas Superstar en color Negro, Blanco.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-014/atl-snk-014-01.jpeg",
            "img/productos/atl-snk-014/atl-snk-014-02.jpeg",
            "img/productos/atl-snk-014/atl-snk-014-03.jpeg",
            "img/productos/atl-snk-014/atl-snk-014-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 15,
        "codigo": "ATL-SNK-015",
        "marca": "Nike",
        "modelo": "Nike Air Max Command",
        "color": "Negro, Rojo, Blanco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Domina la calle con la actitud retro de los Nike Air Max Command, un clásico atemporal que destaca por su contundente contraste en blanco y negro con acentos rojos.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-015/atl-snk-015-01.jpeg",
            "img/productos/atl-snk-015/atl-snk-015-02.jpeg",
            "img/productos/atl-snk-015/atl-snk-015-03.jpeg",
            "img/productos/atl-snk-015/atl-snk-015-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 16,
        "codigo": "ATL-SNK-016",
        "marca": "Nike",
        "modelo": "Nike Shox R4",
        "color": "Gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Eleva tu estilo con la estética retro-futurista de los Nike Shox R4, diseñados en un impecable y versátil tono gris monocromático",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-016/atl-snk-016-01.jpeg",
            "img/productos/atl-snk-016/atl-snk-016-02.jpeg",
            "img/productos/atl-snk-016/atl-snk-016-03.jpeg",
            "img/productos/atl-snk-016/atl-snk-016-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 17,
        "codigo": "ATL-SNK-017",
        "marca": "Puma",
        "modelo": "Puma 180",
        "color": "Negro",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Domina las calles con los imponentes Puma-180, una silueta chunky de inspiración skate en un versátil y agresivo diseño completamente negro.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-017/atl-snk-017-01.webp",
            "img/productos/atl-snk-017/atl-snk-017-02.webp",
            "img/productos/atl-snk-017/atl-snk-017-03.webp",
            "img/productos/atl-snk-017/atl-snk-017-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 18,
        "codigo": "ATL-SNK-018",
        "marca": "Vans",
        "modelo": "Vans Upland",
        "color": "Blanco, verde",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Revive la época dorada del skate con los Vans Upland, una robusta silueta en cuero blanco que resalta con sus detalles y gruesos cordones en verde bosque.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-018/atl-snk-018-01.webp",
            "img/productos/atl-snk-018/atl-snk-018-02.webp",
            "img/productos/atl-snk-018/atl-snk-018-03.webp",
            "img/productos/atl-snk-018/atl-snk-018-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 19,
        "codigo": "ATL-SNK-019",
        "marca": "Adidas",
        "modelo": "adidas Campus 00s",
        "color": "Negro, Blanco",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Captura la auténtica estética skate de los 2000 con los adidas Campus 00s, diseñados en suave gamuza negra con cordones extragruesos de alto contraste.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-019/atl-snk-019-01.webp",
            "img/productos/atl-snk-019/atl-snk-019-02.webp",
            "img/productos/atl-snk-019/atl-snk-019-03.webp",
            "img/productos/atl-snk-019/atl-snk-019-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 20,
        "codigo": "ATL-SNK-020",
        "marca": "New Balance",
        "modelo": "New Balance 9060",
        "color": "Gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Redefine el estilo urbano con los New Balance 9060, una audaz silueta retro-futurista en gamuza premium y malla gris que domina cualquier look",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-020/atl-snk-020-01.webp",
            "img/productos/atl-snk-020/atl-snk-020-02.webp",
            "img/productos/atl-snk-020/atl-snk-020-03.webp",
            "img/productos/atl-snk-020/atl-snk-020-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 21,
        "codigo": "ATL-SNK-021",
        "marca": "Nike",
        "modelo": "Travis x Nike SB Dunk Low",
        "color": "Azul, Beige, Negro",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Marca la diferencia con los legendarios Travis Scott x Nike SB Dunk Low, un ícono urbano que rompe las reglas fusionando estampados de bandana, cuadros y cordones tipo cuerda.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-021/atl-snk-021-01.webp",
            "img/productos/atl-snk-021/atl-snk-021-02.webp",
            "img/productos/atl-snk-021/atl-snk-021-03.webp",
            "img/productos/atl-snk-021/atl-snk-021-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 22,
        "codigo": "ATL-SNK-022",
        "marca": "Adidas",
        "modelo": "Adidas Forum Low",
        "color": "Gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Rompe los esquemas con este innovador diseño utilitario en tonos crema, donde las texturas de gamuza premium se unen a herrajes exclusivos para lograr una estética urbana inigualable.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-022/atl-snk-022-01.webp",
            "img/productos/atl-snk-022/atl-snk-022-02.webp",
            "img/productos/atl-snk-022/atl-snk-022-03.webp",
            "img/productos/atl-snk-022/atl-snk-022-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 23,
        "codigo": "ATL-SNK-023",
        "marca": "Adidas",
        "modelo": "Adidas Superstar",
        "color": "Banco, Gris",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Reinventa tu estilo urbano con estos adidas Superstar, que combinan su icónica puntera de concha con un llamativo maxilogo del trifolio sobre un sutil panel gris.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-023/atl-snk-023-01.webp",
            "img/productos/atl-snk-023/atl-snk-023-02.webp",
            "img/productos/atl-snk-023/atl-snk-023-03.webp",
            "img/productos/atl-snk-023/atl-snk-023-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 24,
        "codigo": "ATL-SNK-024",
        "marca": "Dolce & Gabbana",
        "modelo": "Gabbana",
        "color": "Blanco",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Eleva tu streetwear al nivel del lujo con estos imponentes Dolce & Gabbana, que fusionan un impecable diseño monocromático blanco con llamativos cordones extragruesos.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-024/atl-snk-024-01.webp",
            "img/productos/atl-snk-024/atl-snk-024-02.webp",
            "img/productos/atl-snk-024/atl-snk-024-03.webp",
            "img/productos/atl-snk-024/atl-snk-024-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 25,
        "codigo": "ATL-SNK-025",
        "marca": "Le Coq Sportif",
        "modelo": "Racerone",
        "color": "Negro, Rojo",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Destaca en las calles con la estética retro running de estos Le Coq Sportif, donde la elegancia del negro profundo choca de frente con la energía vibrante de una suela dentada en rojo neón.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-025/atl-snk-025-01.webp",
            "img/productos/atl-snk-025/atl-snk-025-02.webp",
            "img/productos/atl-snk-025/atl-snk-025-03.webp",
            "img/productos/atl-snk-025/atl-snk-025-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 26,
        "codigo": "ATL-SNK-026",
        "marca": "Boss",
        "modelo": "Hugo Boss",
        "color": "Negro",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Proyecta una elegancia absoluta con estos tenis BOSS en un impecable diseño monocromático negro, ideales para quienes buscan un estilo sofisticado y minimalista.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-026/atl-snk-026-01.webp",
            "img/productos/atl-snk-026/atl-snk-026-02.webp",
            "img/productos/atl-snk-026/atl-snk-026-03.webp",
            "img/productos/atl-snk-026/atl-snk-026-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 27,
        "codigo": "ATL-SNK-027",
        "marca": "Louis Vuitton",
        "modelo": "Lv Skate Sneakerd",
        "color": "Negro, Blanco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Lleva el lujo a las calles con los Louis Vuitton LV Skate, una audaz silueta negra que fusiona la estética del skate noventero con la más alta costura.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-027/atl-snk-027-01.webp",
            "img/productos/atl-snk-027/atl-snk-027-02.webp",
            "img/productos/atl-snk-027/atl-snk-027-03.webp",
            "img/productos/atl-snk-027/atl-snk-027-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true,
        "familia": "Calzado",
        "subcategoria": "Tenis"
    },
    {
        "id": 28,
        "codigo": "ATL-SNK-028",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Nike",
        "modelo": "AIR FORCE 1",
        "color": "Azul deslavado, Crema, Azul oscuro",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Destaca en la calle con estos exclusivos Nike Air Force 1, que combinan una base color crema con piezas en azul deslavado y divertidos gráficos en el talón.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-028/atl-snk-028-01.webp",
            "img/productos/atl-snk-028/atl-snk-028-02.webp",
            "img/productos/atl-snk-028/atl-snk-028-03.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-06",
        "activo": true
    },
    {
        "id": 29,
        "codigo": "ATL-SNK-029",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Puma",
        "modelo": "Suede Xl BMW Motorsport",
        "color": "Banco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Acelera tu estilo con esta exclusiva edición BMW Motorsport, que destaca por su silueta robusta, suela de plataforma y cordones extragruesos de estilo urbano.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-029/atl-snk-029-01.webp",
            "img/productos/atl-snk-029/atl-snk-029-02.webp",
            "img/productos/atl-snk-029/atl-snk-029-03.webp",
            "img/productos/atl-snk-029/atl-snk-029-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-06",
        "activo": true
    },
    {
        "id": 30,
        "codigo": "ATL-SNK-030",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Puma",
        "modelo": "Roma",
        "color": "Blanco, Gris, Azul",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Lleva un estilo clásico y deportivo con estos Puma Roma edición BMW, que resaltan por su diseño limpio y su cómoda suela con dientes para que no resbales.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-030/atl-snk-030-01.webp",
            "img/productos/atl-snk-030/atl-snk-030-02.webp",
            "img/productos/atl-snk-030/atl-snk-030-03.webp",
            "img/productos/atl-snk-030/atl-snk-030-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-06",
        "activo": true
    },
    {
        "id": 31,
        "codigo": "ATL-SNK-031",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Boss",
        "modelo": "Botas Hugo Boss",
        "color": "Negro, Rojo",
        "tipo": "Réplica",
        "precio": 210000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Domina las calles con estos tenis tipo bota de HUGO, que combinan tela resistente con una suela muy gruesa y fuerte para que camines seguro.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-031/atl-snk-031-01.webp",
            "img/productos/atl-snk-031/atl-snk-031-02.webp",
            "img/productos/atl-snk-031/atl-snk-031-03.webp",
            "img/productos/atl-snk-031/atl-snk-031-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-06",
        "activo": true
    },
    {
        "id": 32,
        "codigo": "ATL-SNK-032",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Nike",
        "modelo": "AIR FORCE 1 Low",
        "color": "Crema, Gris",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Llama la atención con estos exclusivos Air Force 1, que combinan una base crema con un llamativo patrón de cuadros grises a los costados.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-032/atl-snk-032-01.webp",
            "img/productos/atl-snk-032/atl-snk-032-02.webp",
            "img/productos/atl-snk-032/atl-snk-032-03.webp",
            "img/productos/atl-snk-032/atl-snk-032-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-06",
        "activo": true
    },
    {
        "id": 33,
        "codigo": "ATL-SNK-033",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Vans",
        "modelo": "Retro Lowland",
        "color": "Beige claro",
        "tipo": "Réplica",
        "precio": 195000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Luce un estilo relajado y retro con estos tenis Vans en tono beige, que destacan por su clásico logo lateral y frescos detalles en azul cielo.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-033/atl-snk-033-01.webp",
            "img/productos/atl-snk-033/atl-snk-033-02.webp",
            "img/productos/atl-snk-033/atl-snk-033-03.webp",
            "img/productos/atl-snk-033/atl-snk-033-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-06",
        "activo": true
    },
    {
        "id": 34,
        "codigo": "ATL-SNK-034",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Nike",
        "modelo": "AIR FORCE 1 x Drake",
        "color": "Blanco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Luce un estilo exclusivo con esta edición especial en cuero texturizado, que cambia el clásico logo de la suela por el mensaje romántico \"Love you forever\".",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-034/atl-snk-034-01.webp",
            "img/productos/atl-snk-034/atl-snk-034-02.webp",
            "img/productos/atl-snk-034/atl-snk-034-03.webp",
            "img/productos/atl-snk-034/atl-snk-034-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-06",
        "activo": true
    },
    {
        "id": 35,
        "codigo": "ATL-SNK-035",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Puma",
        "modelo": "Puma Suade XL Motorsport",
        "color": "Crema, Toques Dorados",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Luce un estilo urbano impecable con esta edición especial BMW Motorsport en gamuza texturizada de tono crema.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-035/atl-snk-035-01.webp",
            "img/productos/atl-snk-035/atl-snk-035-02.webp",
            "img/productos/atl-snk-035/atl-snk-035-03.webp",
            "img/productos/atl-snk-035/atl-snk-035-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 36,
        "codigo": "ATL-SNK-036",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Puma",
        "modelo": "Puma Suade XL Motorsport",
        "color": "Azul griceaso, verde Neón",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Destaca con esta audaz edición BMW Motorsport de proporciones exageradas, confeccionada en suave gamuza azul con vibrantes detalles neón.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-036/atl-snk-036-01.webp",
            "img/productos/atl-snk-036/atl-snk-036-02.webp",
            "img/productos/atl-snk-036/atl-snk-036-03.webp",
            "img/productos/atl-snk-036/atl-snk-036-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 37,
        "codigo": "ATL-SNK-037",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Adidas",
        "modelo": "Adidas Response 2",
        "color": "Negro, Blanco",
        "tipo": "Réplica",
        "precio": 195000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Experimenta una pisada ultra suave con estos tenis deportivos gracias a su gruesa entresuela Cloudfoam y exterior de malla ligera transpirable.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-037/atl-snk-037-01.webp",
            "img/productos/atl-snk-037/atl-snk-037-02.webp",
            "img/productos/atl-snk-037/atl-snk-037-03.webp",
            "img/productos/atl-snk-037/atl-snk-037-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 38,
        "codigo": "ATL-SNK-038",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Nike",
        "modelo": "Nike Shox R4",
        "color": "Blanco, Rojo",
        "tipo": "Réplica",
        "precio": 195000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Revive la audacia del año 2000 con su icónico sistema de cuatro pilares en el talón que absorben el impacto y devuelven la energía a cada paso.",
        "categoria": "Deportivo",
        "imagenes": [
            "img/productos/atl-snk-038/atl-snk-038-01.webp",
            "img/productos/atl-snk-038/atl-snk-038-02.webp",
            "img/productos/atl-snk-038/atl-snk-038-03.webp",
            "img/productos/atl-snk-038/atl-snk-038-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 39,
        "codigo": "ATL-SNK-039",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Nike",
        "modelo": "Nike Air Max Plus",
        "color": "Blanco, plata",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Destaca con el estilo atrevido de esta silueta icónica, confeccionada en malla transpirable blanca con dinámicas líneas onduladas plateadas.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-039/atl-snk-039-01.webp",
            "img/productos/atl-snk-039/atl-snk-039-02.webp",
            "img/productos/atl-snk-039/atl-snk-039-03.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 40,
        "codigo": "ATL-SNK-040",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Adidas",
        "modelo": "Adidas Campus",
        "color": "Marrón griceaso, marrón oscuro",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Eleva tu estilo urbano con esta silueta clásica de proporciones robustas, confeccionada en gamuza texturizada con llamativos cordones gruesos.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-040/atl-snk-040-01.webp",
            "img/productos/atl-snk-040/atl-snk-040-02.webp",
            "img/productos/atl-snk-040/atl-snk-040-03.webp",
            "img/productos/atl-snk-040/atl-snk-040-04.webp",
            "img/productos/atl-snk-040/atl-snk-040-05.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 41,
        "codigo": "ATL-SNK-041",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "La Coste",
        "modelo": "T-Clip",
        "color": "Verde oscuro, blanco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Aporta un toque sofisticado a tu look con este exclusivo diseño urbano que fusiona revestimientos lisos y un llamativo patrón geométrico.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-041/atl-snk-041-01.webp",
            "img/productos/atl-snk-041/atl-snk-041-02.webp",
            "img/productos/atl-snk-041/atl-snk-041-03.webp",
            "img/productos/atl-snk-041/atl-snk-041-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 42,
        "codigo": "ATL-SNK-042",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Adidas",
        "modelo": "Adidas Superstar",
        "color": "Blanco, Azul marino",
        "tipo": "Réplica",
        "precio": 195000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Un clásico atemporal que se reinventa con detalles frescos, destacando su inconfundible puntera de concha y franjas laterales en contraste azul.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-042/atl-snk-042-01.webp",
            "img/productos/atl-snk-042/atl-snk-042-02.webp",
            "img/productos/atl-snk-042/atl-snk-042-03.webp",
            "img/productos/atl-snk-042/atl-snk-042-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 43,
        "codigo": "ATL-SNK-043",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "On Running",
        "modelo": "On running cloud",
        "color": "Blanco, Gris, negro mate",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Experimenta la máxima ligereza y tecnología suiza con este diseño aerodinámico confeccionado en malla transpirable de alto rendimiento.",
        "categoria": "Deportivo",
        "imagenes": [
            "img/productos/atl-snk-043/atl-snk-043-01.webp",
            "img/productos/atl-snk-043/atl-snk-043-02.webp",
            "img/productos/atl-snk-043/atl-snk-043-03.webp",
            "img/productos/atl-snk-043/atl-snk-043-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 44,
        "codigo": "ATL-SNK-044",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Adidas",
        "modelo": "Adidas Campus",
        "color": "Crema, marrón claro",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Destaca con esta elegante versión en cuero liso crema que renueva el clásico incorporando franjas laterales texturizadas en relieve y llamativos cordones anchos.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-044/atl-snk-044-01.webp",
            "img/productos/atl-snk-044/atl-snk-044-02.webp",
            "img/productos/atl-snk-044/atl-snk-044-03.webp",
            "img/productos/atl-snk-044/atl-snk-044-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 45,
        "codigo": "ATL-SNK-045",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Adidas",
        "modelo": "Adidas Sl 72",
        "color": "Verde, blanco, azul marino",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Revive la herencia de los 70 con esta silueta retro que fusiona nailon transpirable y resistente gamuza para un estilo urbano inigualable.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-045/atl-snk-045-01.webp",
            "img/productos/atl-snk-045/atl-snk-045-02.webp",
            "img/productos/atl-snk-045/atl-snk-045-03.webp",
            "img/productos/atl-snk-045/atl-snk-045-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 46,
        "codigo": "ATL-SNK-046",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Puma",
        "modelo": "Puma Suade XL Motorsport",
        "color": "Gris claro, Gris oscuro,",
        "tipo": "Réplica",
        "precio": 195000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Acelera tu estilo con esta exclusiva edición automovilística que renueva la silueta clásica con gamuza premium y vibrantes detalles neón.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-046/atl-snk-046-01.webp",
            "img/productos/atl-snk-046/atl-snk-046-02.webp",
            "img/productos/atl-snk-046/atl-snk-046-03.webp",
            "img/productos/atl-snk-046/atl-snk-046-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    },
    {
        "id": 47,
        "codigo": "ATL-SNK-047",
        "familia": "Calzado",
        "subcategoria": "Tenis",
        "marca": "Nike",
        "modelo": "Nike SB Dunk Low",
        "color": "Blanco puro, negro, azul",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Destaca en las calles con esta exclusiva y audaz edición especial que fusiona paneles de cuero liso y granulado con detalles gráficos únicos.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-047/atl-snk-047-01.webp",
            "img/productos/atl-snk-047/atl-snk-047-02.webp",
            "img/productos/atl-snk-047/atl-snk-047-03.webp",
            "img/productos/atl-snk-047/atl-snk-047-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-13",
        "activo": true
    }
];
