/*=========================================================
PROYECTO: ATLAS

ARCHIVO: productos.js

FUNCIÓN:
Almacena la información del catálogo.
Este archivo puede ser actualizado por ATLAS Gestor Local.
=========================================================*/

const productos = [
    {
        "id": 1,
        "codigo": "ATL-SNK-001",
        "marca": "Nike",
        "modelo": "Nike Retro 1 Dior",
        "color": "Azul, gris y blanco",
        "tipo": "Réplica",
        "precio": 210000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker de estilo urbano con silueta retro y una combinación de tonos azules, grises y blancos.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-001/atl-snk-001-01.jpeg",
            "img/productos/atl-snk-001/atl-snk-001-02.jpeg",
            "img/productos/atl-snk-001/atl-snk-001-03.jpeg"
        ],
        "estado": "disponible",
        "destacado": true,
        "fechaCreacion": "2026-07-27",
        "activo": true
    },
    {
        "id": 2,
        "codigo": "ATL-SNK-002",
        "marca": "Adidas",
        "modelo": "Adidas Yeezy",
        "color": "Gris, negro, verde, azul y naranja",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker de perfil robusto y estética deportiva, presentado en una combinación multicolor.",
        "categoria": "Deportivo",
        "imagenes": [
            "img/productos/atl-snk-002/atl-snk-002-01.jpeg",
            "img/productos/atl-snk-002/atl-snk-002-02.jpeg",
            "img/productos/atl-snk-002/atl-snk-002-03.jpeg",
            "img/productos/atl-snk-002/atl-snk-002-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": true,
        "fechaCreacion": "2026-07-27",
        "activo": true
    },
    {
        "id": 3,
        "codigo": "ATL-SNK-003",
        "marca": "Clemont",
        "modelo": "Clemont",
        "color": "Negro y rojo",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker urbano negro con detalles rojos de alto contraste y una estética fuerte y distintiva.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-003/atl-snk-003-01.jpeg",
            "img/productos/atl-snk-003/atl-snk-003-02.jpeg",
            "img/productos/atl-snk-003/atl-snk-003-03.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-07-27",
        "activo": true
    },
    {
        "id": 4,
        "codigo": "ATL-SNK-004",
        "marca": "Vans",
        "modelo": "Vans Old Skool",
        "color": "Negro",
        "tipo": "Réplica",
        "precio": 210000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker urbano en color negro total, con diseño Old Skool y acabado monocromático.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-004/atl-snk-004-01.jpeg",
            "img/productos/atl-snk-004/atl-snk-004-02.jpeg",
            "img/productos/atl-snk-004/atl-snk-004-03.jpeg",
            "img/productos/atl-snk-004/atl-snk-004-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-07-28",
        "activo": true
    },
    {
        "id": 5,
        "codigo": "ATL-SNK-005",
        "marca": "Timberland",
        "modelo": "Boots Timberland",
        "color": "Amarillo Trigo",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Botas Timberland clásicas en color amarillo trigo, con un diseño icónico de caña alta, estilo robusto y versátil, ideal para combinar con atuendos urbanos y casuales.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-005/atl-snk-005-01.jpeg",
            "img/productos/atl-snk-005/atl-snk-005-02.jpeg",
            "img/productos/atl-snk-005/atl-snk-005-03.jpeg",
            "img/productos/atl-snk-005/atl-snk-005-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-07-29",
        "activo": true
    },
    {
        "id": 6,
        "codigo": "ATL-SNK-006",
        "marca": "Nike",
        "modelo": "Air Jordan Retro 3",
        "color": "blanco, beige, gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Los Air Jordán 3 Retro combinan el legendario estampado de elefante con la máxima comodidad del Streetwear.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-006/atl-snk-006-01.jpeg",
            "img/productos/atl-snk-006/atl-snk-006-02.jpeg",
            "img/productos/atl-snk-006/atl-snk-006-03.jpeg",
            "img/productos/atl-snk-006/atl-snk-006-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-07-29",
        "activo": true
    },
    {
        "id": 7,
        "codigo": "ATL-SNK-007",
        "marca": "On Running",
        "modelo": "On Cloudflow",
        "color": "azul, gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Corre como nunca antes con la elegancia técnica y el diseño bicolor de las On Cloudflow. La máxima potencia de la espuma Helion se une a la icónica suela CloudTec para un rendimiento explosivo",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-007/atl-snk-007-01.jpeg",
            "img/productos/atl-snk-007/atl-snk-007-02.jpeg",
            "img/productos/atl-snk-007/atl-snk-007-03.jpeg",
            "img/productos/atl-snk-007/atl-snk-007-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 8,
        "codigo": "ATL-SNK-008",
        "marca": "Puma",
        "modelo": "Puma 180",
        "color": "Gris, Blanco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Silueta *chunky* retro que fusiona malla transpirable, cuero y gamuza gris. El equilibrio perfecto entre comodidad robusta y estilo urbano.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-008/atl-snk-008-01.jpeg",
            "img/productos/atl-snk-008/atl-snk-008-02.jpeg",
            "img/productos/atl-snk-008/atl-snk-008-03.jpeg",
            "img/productos/atl-snk-008/atl-snk-008-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 9,
        "codigo": "ATL-SNK-009",
        "marca": "Osiris",
        "modelo": "Osiris",
        "color": "Negros",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Domina la calle con la legendaria silueta chunky de los Osiris, diseñados en gamuza negra con cordones blancos de alto contraste para un estilo urbano imponente.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-009/atl-snk-009-01.jpeg",
            "img/productos/atl-snk-009/atl-snk-009-02.jpeg",
            "img/productos/atl-snk-009/atl-snk-009-03.jpeg",
            "img/productos/atl-snk-009/atl-snk-009-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 10,
        "codigo": "ATL-SNK-010",
        "marca": "Boss",
        "modelo": "Hugo Boss",
        "color": "Negro, Rojo",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Destaca con la elegancia urbana de estos tenis BOSS, diseñados en negro profundo con un llamativo patrón tipográfico y exclusivos acentos en rojo vibrante.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-010/atl-snk-010-01.jpeg",
            "img/productos/atl-snk-010/atl-snk-010-02.jpeg",
            "img/productos/atl-snk-010/atl-snk-010-03.jpeg",
            "img/productos/atl-snk-010/atl-snk-010-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 11,
        "codigo": "ATL-SNK-011",
        "marca": "Nike, Supreme",
        "modelo": "Supreme x Nike Shox Ride 2",
        "color": "Rojo",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Desata tu lado más audaz con los exclusivos Supreme x Nike Shox Ride 2, una silueta retro en rojo vibrante llena de actitud streetwear.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-011/atl-snk-011-01.jpeg",
            "img/productos/atl-snk-011/atl-snk-011-02.jpeg",
            "img/productos/atl-snk-011/atl-snk-011-03.jpeg",
            "img/productos/atl-snk-011/atl-snk-011-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 12,
        "codigo": "ATL-SNK-012",
        "marca": "Le Coq Sportif",
        "modelo": "Lecoq Sportif",
        "color": "Negro",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Eleva tu estilo urbano con la elegancia atemporal de estos Le Coq Sportif, diseñados en un sofisticado negro mate con deslumbrantes acentos dorados.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-012/atl-snk-012-01.jpeg",
            "img/productos/atl-snk-012/atl-snk-012-02.jpeg",
            "img/productos/atl-snk-012/atl-snk-012-03.jpeg",
            "img/productos/atl-snk-012/atl-snk-012-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 13,
        "codigo": "ATL-SNK-013",
        "marca": "Puma",
        "modelo": "Puma Club 5v5",
        "color": "Beige, Verde",
        "tipo": "Réplica",
        "precio": 210000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Dale un toque vintage a tus pasos con esta clásica silueta de Puma, diseñada en un elegante tono crema con suaves superposiciones de gamuza y su icónica franja en contraste verde.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-013/atl-snk-013-01.jpeg",
            "img/productos/atl-snk-013/atl-snk-013-02.jpeg",
            "img/productos/atl-snk-013/atl-snk-013-03.jpeg",
            "img/productos/atl-snk-013/atl-snk-013-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 14,
        "codigo": "ATL-SNK-014",
        "marca": "Adidas, NEIGHBORHOOD",
        "modelo": "adidas Superstar",
        "color": "Negro, Blanco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Sneaker Adidas, NEIGHBORHOOD adidas Superstar en color Negro, Blanco.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-014/atl-snk-014-01.jpeg",
            "img/productos/atl-snk-014/atl-snk-014-02.jpeg",
            "img/productos/atl-snk-014/atl-snk-014-03.jpeg",
            "img/productos/atl-snk-014/atl-snk-014-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 15,
        "codigo": "ATL-SNK-015",
        "marca": "Nike",
        "modelo": "Nike Air Max Command",
        "color": "Negro, Rojo, Blanco",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Domina la calle con la actitud retro de los Nike Air Max Command, un clásico atemporal que destaca por su contundente contraste en blanco y negro con acentos rojos.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-015/atl-snk-015-01.jpeg",
            "img/productos/atl-snk-015/atl-snk-015-02.jpeg",
            "img/productos/atl-snk-015/atl-snk-015-03.jpeg",
            "img/productos/atl-snk-015/atl-snk-015-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 16,
        "codigo": "ATL-SNK-016",
        "marca": "Nike",
        "modelo": "Nike Shox R4",
        "color": "Gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Eleva tu estilo con la estética retro-futurista de los Nike Shox R4, diseñados en un impecable y versátil tono gris monocromático",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-016/atl-snk-016-01.jpeg",
            "img/productos/atl-snk-016/atl-snk-016-02.jpeg",
            "img/productos/atl-snk-016/atl-snk-016-03.jpeg",
            "img/productos/atl-snk-016/atl-snk-016-04.jpeg"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 17,
        "codigo": "ATL-SNK-017",
        "marca": "Puma",
        "modelo": "Puma 180",
        "color": "Negro",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Domina las calles con los imponentes Puma-180, una silueta chunky de inspiración skate en un versátil y agresivo diseño completamente negro.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-017/atl-snk-017-01.webp",
            "img/productos/atl-snk-017/atl-snk-017-02.webp",
            "img/productos/atl-snk-017/atl-snk-017-03.webp",
            "img/productos/atl-snk-017/atl-snk-017-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-01",
        "activo": true
    },
    {
        "id": 18,
        "codigo": "ATL-SNK-018",
        "marca": "Vans",
        "modelo": "Vans Upland",
        "color": "Blanco, verde",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Revive la época dorada del skate con los Vans Upland, una robusta silueta en cuero blanco que resalta con sus detalles y gruesos cordones en verde bosque.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-018/atl-snk-018-01.webp",
            "img/productos/atl-snk-018/atl-snk-018-02.webp",
            "img/productos/atl-snk-018/atl-snk-018-03.webp",
            "img/productos/atl-snk-018/atl-snk-018-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true
    },
    {
        "id": 19,
        "codigo": "ATL-SNK-019",
        "marca": "Adidas",
        "modelo": "adidas Campus 00s",
        "color": "Negro, Blanco",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Captura la auténtica estética skate de los 2000 con los adidas Campus 00s, diseñados en suave gamuza negra con cordones extragruesos de alto contraste.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-019/atl-snk-019-01.webp",
            "img/productos/atl-snk-019/atl-snk-019-02.webp",
            "img/productos/atl-snk-019/atl-snk-019-03.webp",
            "img/productos/atl-snk-019/atl-snk-019-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true
    },
    {
        "id": 20,
        "codigo": "ATL-SNK-020",
        "marca": "New Balance",
        "modelo": "New Balance 9060",
        "color": "Gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Redefine el estilo urbano con los New Balance 9060, una audaz silueta retro-futurista en gamuza premium y malla gris que domina cualquier look",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-020/atl-snk-020-01.webp",
            "img/productos/atl-snk-020/atl-snk-020-02.webp",
            "img/productos/atl-snk-020/atl-snk-020-03.webp",
            "img/productos/atl-snk-020/atl-snk-020-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true
    },
    {
        "id": 21,
        "codigo": "ATL-SNK-021",
        "marca": "Nike",
        "modelo": "Travis x Nike SB Dunk Low",
        "color": "Azul, Beige, Negro",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Marca la diferencia con los legendarios Travis Scott x Nike SB Dunk Low, un ícono urbano que rompe las reglas fusionando estampados de bandana, cuadros y cordones tipo cuerda.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-021/atl-snk-021-01.webp",
            "img/productos/atl-snk-021/atl-snk-021-02.webp",
            "img/productos/atl-snk-021/atl-snk-021-03.webp",
            "img/productos/atl-snk-021/atl-snk-021-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true
    },
    {
        "id": 22,
        "codigo": "ATL-SNK-022",
        "marca": "Adidas",
        "modelo": "Adidas Forum Low",
        "color": "Gris",
        "tipo": "Réplica",
        "precio": 200000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Rompe los esquemas con este innovador diseño utilitario en tonos crema, donde las texturas de gamuza premium se unen a herrajes exclusivos para lograr una estética urbana inigualable.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-022/atl-snk-022-01.webp",
            "img/productos/atl-snk-022/atl-snk-022-02.webp",
            "img/productos/atl-snk-022/atl-snk-022-03.webp",
            "img/productos/atl-snk-022/atl-snk-022-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true
    },
    {
        "id": 23,
        "codigo": "ATL-SNK-023",
        "marca": "Adidas",
        "modelo": "Adidas Superstar",
        "color": "Banco, Gris",
        "tipo": "Réplica",
        "precio": 190000,
        "moneda": "COP",
        "tallas": [
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44
        ],
        "sistemaTallas": "EUR",
        "confirmarDisponibilidad": true,
        "descripcion": "Reinventa tu estilo urbano con estos adidas Superstar, que combinan su icónica puntera de concha con un llamativo maxilogo del trifolio sobre un sutil panel gris.",
        "categoria": "Urbano",
        "imagenes": [
            "img/productos/atl-snk-023/atl-snk-023-01.webp",
            "img/productos/atl-snk-023/atl-snk-023-02.webp",
            "img/productos/atl-snk-023/atl-snk-023-03.webp",
            "img/productos/atl-snk-023/atl-snk-023-04.webp"
        ],
        "estado": "disponible",
        "destacado": false,
        "fechaCreacion": "2026-08-04",
        "activo": true
    }
];
